### ISSUE TITLE
 need python for node-gyp

### ISSUE THREAD

**Issue by united0202** [AndreySenov/firebase-tools-docker#1]
Python is required for node-gyp. When I try to install it on myself in "before_scripts", I get an error related to permission. Try different options but overall it looks like this (https://prnt.sc/pwyzq6).
I found in the dockerfile that you are changing the user  (USER node) . Perhaps that’s why I can’t do anything about it. Could you add a Python or help me solve my problem? Thank you.

**Comment by united0202** [comment]
yes, I guess I have a multistage build. Something like this : 
Sorry, I'm just not competent enough in this, because I definitely can’t tell you.


install backend:
  stage: install
  cache:
    key: BE-$CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - functions/node_modules/
  script:
    - cd functions
    - npm ci

install frontend:
  stage: install
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /ci:only-backend/ # don't run this stage if commit message includes 'ci:only-backend'
  cache:
    key: FE-$CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
  script:
    - npm ci

build backend:
  stage: build
  cache:
    key: BE-$CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - functions/node_modules/
    policy: pull
  script:
    - cd functions
    - ./node_modules/.bin/tslint -p tslint.json
    - ./node_modules/.bin/tsc
    - cp ../privatekey.pem ./lib
    #- (if [ "$CI_COMMIT_MESSAGE" =~ /^ci:only-backend*/ ]; then echo "Note, ci:only-backend tag will NOT update 'App last updated:' on settings page" ; fi);
  artifacts: # store results of build
    expire_in: 1 week
    paths:
      - functions/lib/

**Comment by AndreySenov** [comment]
I decided to create a separate image containing `node-gyp` and the toolchain since I believe it isn't a good idea to add `python` to the `firebase-tools` image. Please try to use this to build your project:
https://hub.docker.com/r/andreysenov/node-gyp

**Comment by AndreySenov** [comment]
Python 3 has been part of the image since the release 12.0.0
