### ISSUE TITLE
Node 14

### ISSUE THREAD

**Issue by sw-tracker** [AndreySenov/firebase-tools-docker#12]
Firebase supports node 14. It would be nice to have an image with node 14.

Thanks!

**Comment by AndreySenov** [comment]
Hi @sw-tracker ,

Node 14 is current LTS version. The image tagged as `latest` is always built on `node:lts-alpine`.
Thus, all you need is `docker pull andreysenov/firebase-tools`.

**Comment by felixgabler** [comment]
Latest now points to Node.js v16. Can we have a build for 14?

**Comment by AndreySenov** [comment]
Hi @felixgabler ,

Sure, please use `latest-node-14` tag.
