### ISSUE TITLE
FYI: latest (9.16.2) and 9.16.1 generates revoked id tokens on auth emulator

### ISSUE THREAD

**Issue by juanlacostepager** [AndreySenov/firebase-tools-docker#16]
Hi! I use your image to perform integration testing on a service that uses firebase auth. Yesterday mi CI pipeline started to fail on tests that were using firebase SDK (admin and client) to simulate login and verifying id tokens. I found that images from 9.16.1 to latest are throwing the error `auth/id-token-revoked` when I try to verify an Id token generated by the emulator suite.

When I debug the token generated with jwt.io, i see that the expiration time is one hour after it was generated...but it fails the `verifyIdtoken` invocation with error "The ID token was revoked"

Reverting to 9.16.0 Image solved the issue.

**Comment by steinroe** [comment]
This is a problem with firebase-tools: https://github.com/firebase/firebase-tools/issues/3673

**Comment by juanlacostepager** [comment]
Awesome, good to know. Thanks for your help. I look forward to the updated version 😄
