### ISSUE TITLE
Speed up emulator launch?

### ISSUE THREAD

**Issue by ScottPierce** [AndreySenov/firebase-tools-docker#25]
So when I run emulators on my local machine without docker, it starts up in less than 3 seconds. When I run it through docker, it takes 20-30 seconds to start. Any idea what can be done to speed it up?

**Comment by mayteio** [comment]
+1 for this. Often I get
```
Error: Failed to make request to https://firebase-public.firebaseio.com/cli.json
```
And I have to restart it for it to successfully start up.
