### ISSUE TITLE
Build for arm64

### ISSUE THREAD

**Issue by keeth** [AndreySenov/firebase-tools-docker#29]
It would be great to have an ARM64 image for Apple M1 laptops. Thanks!

**Comment by alexjball** [comment]
#30 builds for arm64. For now, you can access an arm64 image [here](https://hub.docker.com/r/alexjball/firebase-tools)

**Comment by ScottPierce** [comment]
@AndreySenov It'd be great to get official support for this. The startup time for this image on m1's is VERY slow. More than a minute to get things running.

**Comment by trhodeos** [comment]
Gave this another go in #36 , images [here](https://hub.docker.com/repository/docker/trhodes/firebase-tools/tags?page=1&ordering=last_updated)
