### ISSUE TITLE
firebase-tools version 11.14.0 has broken only hosting deployments

### ISSUE THREAD

**Issue by GaroX** [AndreySenov/firebase-tools-docker#33]
Hi

firebase-tools version 11.14.0 has broken only hosting deployments:

Error: Failed to list functions for <project>.

the project only uses hosting and I do the manual deployment from my computer with version 11.13.0 and it works without problems.

I use image: andreysenov/firebase-tools:latest-node-14

my deployment is like this:
1. npm ci
2. npm run build 
3. firebase use $PROJECT_NAME --token $FIREBASE_TOKEN
4.firebase deploy --only hosting -m "......" --token $FIREBASE_TOKEN

pls help!
![Captura de Pantalla 2022-10-05 a la(s) 9 52 28 p m](https://user-images.githubusercontent.com/6117247/194203533-5c4c7e6f-2c56-4446-b47c-45f637a4c840.png)

**Comment by AndreySenov** [comment]
Hi @GaroX ,

Please try to use the latest version. According to release notes, there were some fixes related to deployment.
