### ISSUE TITLE
Authentication port shall be 9099 instead of 9005 ?

### ISSUE THREAD

**Issue by seijik42** [AndreySenov/firebase-tools-docker#9]
Hi, thank you for maintaining this.

In firebase document, default port of Authentication is 9099
https://firebase.google.com/docs/emulator-suite/install_and_configure
But in this project 9005 is used instead. Is there any reason behind it?
If I need to use different port for Auth, I believe I need to specify it in firebase.json

In the internet, seems like 9005 is also used for some login purposes? However I couldn't find Google official doc mentioning it.

**Comment by AndreySenov** [comment]
Hi @seijik42 ,

Thank you for your feedback.

The image doesn't force to use specific port numbers but [exposes](https://docs.docker.com/engine/reference/builder/#expose) default values used by Firebase CLI and the emulators.
The port `9005` is used for authentication within `firebase login` command. The port `9099` is default one used by the Authentication Emulator, the image didn't have this value `exposed`. I've corrected this.

**Comment by seijik42** [comment]
@AndreySenov 
Thanks! Now it is totally clear to me. Thank you for adding it as well.
